### ISSUE TITLE
Every O/L attempt must have its own index number

### ISSUE THREAD

**Issue by Dinujaya-Sandaruwan** [dinethsiriwardana/AL-Application-System#2]
<img width="466" alt="image" src="https://github.com/user-attachments/assets/23d0c173-1a4c-4d67-a787-c9a7d33f5cb8">

**Comment by Dinujaya-Sandaruwan** [comment]
### Use name "indexNo" to store it

**Comment by dinethsiriwardana** [comment]
index_no: { type: String; required: false };


added, send the data through the API.
